name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
        REACT_APP_SPLITWISE_API_TOKEN: ${{ secrets.REACT_APP_SPLITWISE_API_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4.1.5
      with:
        BRANCH: gh-pages
        FOLDER: build
